version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask-app:
    build:
      context: .
    container_name: asm_web
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./app:/app
    restart: always

volumes:
  mongo_data:
