  version: '3.9'

  services:
    mongo:
      image: mongo
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
    redis:
      image: redis:7-alpine
      ports: ["6379:6379"]
      volumes:
        - redis_data:/data

    celery-worker:
      build: .
      command: celery -A app.celery_app worker --loglevel=info
      depends_on:
        - redis
        - mongo
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/1
        - PYTHONPATH=/usr/src/app
      env_file:
        - .env
    celery-beat:
      build: .
      command: celery -A app.celery_app beat --loglevel=info
      depends_on:
        - redis
      environment:
        - PYTHONPATH=/usr/src/app
      env_file:
        - .env
    flask-app:
      build:
        context: .
      container_name: asm_web
      ports:
        - "5000:5000"
      depends_on:
        - mongo
      env_file:
        - .env
      volumes:
        - ./app:/app
      restart: always

  volumes:
    mongo_data:
    redis_data: